### ISSUE TITLE
Nested inview components?

### ISSUE THREAD

**Issue by oneezy** [maciekgrzybek/svelte-inview#21]
Hi again!

I'm trying to get this nested _ScrollSpy_ `<Component />` working inside itself but having some issues. 
https://svelte.dev/repl/b19d297fc3a44719b9d2b7dc881ebeb7?version=3.48.0

I tried using <svelte:self /> but I don't think I'm doing it correctly.

The issue as you'll see is that "Section 2" isn't staying active (only the children sections become active)

**Comment by maciejgrzybek-ramp** [comment]
Sorry, was really busy for the last 2 weeks. Ok, so:
- `svelte:self` won't work here, it's doing something else
- you check if the element is active by comparing id to the href `class:active={`#${$activeSectionId}` === href}` - this won't be true for the parents (because `section2a !== section2`
- you need to find a different way to compare it, maybe create a separate component `ParentSectionLink` that will check the regex instead

**Comment by maciekgrzybek** [comment]
Sorry, was really busy for the last 2 weeks. Ok, so:
- `svelte:self` won't work here, it's doing something else
- you check if the element is active by comparing id to the href `class:active={`#${$activeSectionId}` === href}` - this won't be true for the parents (because `section2a !== section2`
- you need to find a different way to compare it, maybe create a separate component `ParentSectionLink` that will check the regex instead

**Comment by maciekgrzybek** [comment]
Closing this one :) Let me know if it's sorted :)
